import React, { useState } from 'react';
import {
  X,
  Printer,
  Download,
  FileText,
  Code2,
  Check,
  Copy,
  ShieldCheck,
  MapPin,
  Calendar,
  Globe2,
} from 'lucide-react';
import { EarthReport, SupportedLanguage } from '../types';

interface ReportExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  language: SupportedLanguage;
  report: EarthReport;
}

export const ReportExportModal: React.FC<ReportExportModalProps> = ({
  isOpen,
  onClose,
  language,
  report,
}) => {
  const isRtl = language === 'fa';
  const [copiedType, setCopiedType] = useState<string | null>(null);

  if (!isOpen) return null;

  // Generate Markdown
  const markdownText = `# "Why Here" YouTube Earth Observation Dossier: ${report.title}
**Case ID:** ${report.id}
**Channel:** ${report.channel}
**Location:** ${report.location.name} (${report.location.coordinates})
**Elevation:** ${report.location.elevation || 'N/A'}
**Vault Hash:** ${report.vaultHash}
**Generated Date:** ${new Date(report.createdAt).toUTCString()}

---

## 1. Master Narration Script (English)
${report.paraphrasedScriptEn}

---

## 2. فیلم‌نامه و گویندگی فارسی
${report.paraphrasedScriptFa}

---

## 3. Earth Observation Storyboard Breakdown
${(report.storyboardFrames || [])
  .map(
    (f, idx) =>
      `### Shot ${idx + 1} (${f.timecode}): ${f.title}\n- **Type:** ${f.type}\n- **Prompt:** ${f.prompt}\n- **HUD Overlay:** ${f.visualOverlay}`
  )
  .join('\n\n')}

---

## 4. Quantitative Historical Trends (1984 - 2026)
| Year | Water Area (km²) | Salinity (g/L) | NDVI Anomaly | Milestone Event |
|---|---|---|---|---|
${(report.historicalTrends || [])
  .map((t) => `| ${t.year} | ${t.waterAreaKm2} | ${t.salinityGPerL} | ${t.ndviAnomaly} | ${t.event} |`)
  .join('\n')}

---
*Generated by Why Here Earth Observation Studio - Verified Cryptographic Storage*
`;

  const handleDownloadMarkdown = () => {
    const blob = new Blob([markdownText], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `WhyHere_${report.id}_Dossier.md`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadJson = () => {
    const blob = new Blob([JSON.stringify(report, null, 2)], { type: 'application/json;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `WhyHere_${report.id}_Archive.json`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/85 p-4 backdrop-blur-md">
      <div className="relative w-full max-w-4xl rounded-2xl border border-cyan-500/30 bg-slate-900 shadow-2xl overflow-hidden flex flex-col max-h-[90vh]">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-slate-800 bg-slate-950/80 px-6 py-4">
          <div className="flex items-center gap-3">
            <div className="flex h-9 w-9 items-center justify-center rounded-lg border border-cyan-500/40 bg-cyan-950/40 text-cyan-400">
              <Download className="h-5 w-5" />
            </div>
            <div>
              <h2 className="text-base font-bold text-white">
                {isRtl ? 'خروجی پرونده کامل گزارش ماهواره‌ای' : 'Export Full Earth Observation Dossier'}
              </h2>
              <p className="text-xs text-slate-400">
                {isRtl
                  ? 'شامل فیلم‌نامه دوزبانه، کدهای استوری‌بورد، جداول تاریخی و امضای رمزنگاری'
                  : 'Includes bilingual scripts, storyboard cues, timeline datasets, and cryptoseal'}
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 rounded-lg border border-slate-800 bg-slate-950 px-3 py-1.5 text-xs text-slate-300 hover:text-white transition"
            >
              <Printer className="h-3.5 w-3.5 text-cyan-400" />
              <span>{isRtl ? 'چاپ / PDF' : 'Print / PDF'}</span>
            </button>

            <button
              onClick={handleDownloadMarkdown}
              className="flex items-center gap-1.5 rounded-lg border border-cyan-500/40 bg-cyan-950/50 px-3 py-1.5 text-xs text-cyan-300 hover:bg-cyan-900/60 transition"
            >
              <FileText className="h-3.5 w-3.5" />
              <span>Markdown</span>
            </button>

            <button
              onClick={handleDownloadJson}
              className="flex items-center gap-1.5 rounded-lg border border-slate-800 bg-slate-950 px-3 py-1.5 text-xs text-slate-300 hover:text-white transition"
            >
              <Code2 className="h-3.5 w-3.5" />
              <span>JSON</span>
            </button>

            <button
              onClick={onClose}
              className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-800 hover:text-white transition ml-2"
            >
              <X className="h-5 w-5" />
            </button>
          </div>
        </div>

        {/* Printable Preview Document */}
        <div className="flex-1 overflow-y-auto p-6 sm:p-8 space-y-6 bg-slate-950 text-slate-200 print:bg-white print:text-black">
          {/* Document Header */}
          <div className="border-b border-cyan-500/30 pb-4">
            <div className="flex items-center justify-between font-mono text-xs text-cyan-400">
              <span>PROJECT DOSSIER: {report.id}</span>
              <span className="flex items-center gap-1 text-emerald-400">
                <ShieldCheck className="h-3.5 w-3.5" />
                {report.vaultHash ? report.vaultHash.slice(0, 24) + '...' : 'Verified Vault Record'}
              </span>
            </div>
            <h1 className="mt-2 text-xl sm:text-2xl font-bold text-white font-['Space_Grotesk'] leading-tight print:text-black">
              {report.title}
            </h1>
            <p dir="rtl" className="mt-1 text-base text-slate-300 font-persian print:text-gray-700">
              {report.titleFa}
            </p>

            <div className="mt-3 flex flex-wrap items-center gap-4 text-xs font-mono text-slate-400">
              <span className="flex items-center gap-1">
                <MapPin className="h-3.5 w-3.5 text-cyan-400" />
                {report.location.name} [{report.location.coordinates}]
              </span>
              <span>Elevation: {report.location.elevation || 'N/A'}</span>
              <span>Category: {report.category}</span>
              <span>Channel: {report.channel}</span>
            </div>
          </div>

          {/* Scripts */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="rounded-xl border border-slate-800 bg-slate-900/60 p-4 print:border-gray-300">
              <h3 className="text-xs font-mono text-cyan-400 uppercase tracking-wider mb-2 font-bold">
                Narration Script (English) - "Why Here" Format
              </h3>
              <p className="text-xs sm:text-sm text-slate-300 leading-relaxed font-['Plus_Jakarta_Sans'] whitespace-pre-line print:text-black">
                {report.paraphrasedScriptEn}
              </p>
            </div>

            <div dir="rtl" className="rounded-xl border border-slate-800 bg-slate-900/60 p-4 font-persian print:border-gray-300">
              <h3 className="text-xs font-mono text-emerald-400 uppercase tracking-wider mb-2 font-bold font-sans">
                فیلم‌نامه و متن گویندگی فارسی
              </h3>
              <p className="text-xs sm:text-sm text-slate-200 leading-loose whitespace-pre-line print:text-black">
                {report.paraphrasedScriptFa}
              </p>
            </div>
          </div>

          {/* Historical Trends Table */}
          <div className="rounded-xl border border-slate-800 bg-slate-900/60 p-4">
            <h3 className="text-xs font-mono text-cyan-400 uppercase tracking-wider mb-3 font-bold">
              Quantitative Satellite Observation Telemetry (1984 - 2026)
            </h3>
            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs font-mono">
                <thead>
                  <tr className="border-b border-slate-800 text-slate-400">
                    <th className="py-2">Year</th>
                    <th className="py-2">Water Area</th>
                    <th className="py-2">Salinity</th>
                    <th className="py-2">NDVI</th>
                    <th className="py-2">Milestone Observation</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-800/60 text-slate-300">
                  {(report.historicalTrends || []).map((t) => (
                    <tr key={t.year}>
                      <td className="py-2 font-bold text-cyan-400">{t.year}</td>
                      <td className="py-2">{t.waterAreaKm2 ? `${t.waterAreaKm2} km²` : '-'}</td>
                      <td className="py-2">{t.salinityGPerL ? `${t.salinityGPerL} g/L` : '-'}</td>
                      <td className="py-2 text-emerald-400">{t.ndviAnomaly}</td>
                      <td className="py-2 text-slate-400">{t.event}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
